---
# Python 3 with Redis
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    ports:
      - 5000:5000
    volumes:
      - ..:/app
      - ~/.ssh/:/home/devops/.ssh/
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - dev
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - dev

volumes:
  redis_data:

networks:
  dev:
